# Generated by Django 3.2 on 2023-02-15 13:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=32)),
                ('model', models.CharField(max_length=32)),
                ('quantity', models.IntegerField()),
                ('recomended_quantity', models.IntegerField()),
                ('document', models.FileField(blank=True, null=True, upload_to='uploads/%Y%m%d/')),
            ],
        ),
        migrations.CreateModel(
            name='DrumRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drum_name', models.CharField(choices=[('CF219A', 'CF219A'), ('CF257A', 'CF257A'), ('DR-2401', 'DR-2401'), ('DR-2100', 'DR-2100'), ('MLT-R204', 'MLT-R204')], default='none', max_length=150)),
                ('quantity', models.IntegerField()),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=70, null=True)),
                ('internet', models.CharField(choices=[('Y', 'Да'), ('N', 'Не')], default='N', max_length=5)),
                ('shares_access', models.CharField(choices=[('none', 'none'), ('Off', 'Off'), ('OFI', 'OFI'), ('IT', 'IT'), ('oldpcs', 'oldpcs')], default='none', max_length=10)),
                ('place_of_work', models.CharField(choices=[('Plovdiv', 'Plovdiv'), ('Graf Ignatievo', 'Graf Ignatievo'), ('Krumovo', 'Krumovo')], default='Plovdiv', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Toner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=32)),
                ('model', models.CharField(max_length=32)),
                ('quantity', models.IntegerField()),
                ('recomended_quantity', models.IntegerField()),
                ('document', models.FileField(blank=True, null=True, upload_to='uploads/%Y%m%d/')),
            ],
        ),
        migrations.CreateModel(
            name='TonerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cartridge_name', models.CharField(choices=[('W1106A (106A)', 'W1106A (106A)'), ('CRG-724 H', 'CRG-724 H'), ('CRG-057 H', 'CRG-057 H'), ('CE285A', 'CE285A'), ('MLT-D204E', 'MLT-D204E'), ('4422810010', '4422810010'), ('CF217A', 'CF217A'), ('TK-130', 'TK-130'), ('953XL/957XL black', '953XL/957XL black'), ('CF410X Black', 'CF410X Black'), ('CF411X Cyan', 'CF411X Cyan'), ('CF412X Yellow', 'CF412X Yellow'), ('CF413X Magenta', 'CF413X Magenta'), ('LP-4240', 'LP-4240'), ('BTD60BK and BT5000M/C/Y', 'BTD60BK and BT5000M/C/Y'), ('TN-2421', 'TN-2421'), ('613511010', '613511010'), ('TK-1140', 'TK-1140'), ('CB436A', 'CB436A'), ('CRG-719', 'CRG-719'), ('CF226X', 'CF226X'), ('Q2612X', 'Q2612X'), ('613511015', '613511015'), ('CF283A', 'CF283A'), ('MLT-D2082L', 'MLT-D2082L'), ('MLT-D208L', 'MLT-D208L'), ('CE278A', 'CE278A'), ('TN-2120', 'TN-2120'), ('CB435A', 'CB435A'), ('CF256A', 'CF256A'), ('9004391', '9004391')], default='none', max_length=150)),
                ('quantity', models.IntegerField()),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=32)),
                ('model', models.CharField(max_length=32)),
                ('serial_number', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('mac_address', models.CharField(blank=True, max_length=20, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='uploads/%Y%m%d/')),
                ('drum', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='app.drum')),
                ('toner', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='app.toner')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='app.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=32)),
                ('model', models.CharField(max_length=32)),
                ('serial_number', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('size', models.CharField(blank=True, max_length=10, null=True)),
                ('ports', models.CharField(blank=True, max_length=50, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='uploads/%Y%m%d/')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='app.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=32)),
                ('model', models.CharField(max_length=32)),
                ('serial_number', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('cpu', models.CharField(blank=True, max_length=20, null=True)),
                ('ram', models.CharField(blank=True, max_length=10, null=True)),
                ('video_card', models.CharField(blank=True, max_length=20, null=True)),
                ('drive', models.CharField(blank=True, max_length=20, null=True)),
                ('mac_address', models.CharField(blank=True, max_length=20, null=True)),
                ('wifi_mac_address', models.CharField(blank=True, max_length=20, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='uploads/%Y%m%d/')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='app.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=32)),
                ('model', models.CharField(max_length=32)),
                ('serial_number', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('cpu', models.CharField(blank=True, max_length=20, null=True)),
                ('ram', models.CharField(blank=True, max_length=10, null=True)),
                ('drive', models.CharField(blank=True, max_length=20, null=True)),
                ('video_card', models.CharField(blank=True, max_length=20, null=True)),
                ('mac_address', models.CharField(blank=True, max_length=20, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='uploads/%Y%m%d/')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='app.employee')),
            ],
        ),
    ]
