# Generated by Django 4.1.2 on 2022-12-06 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('mobile', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=70)),
                ('place_of_work', models.CharField(choices=[('Plovdiv', 'Plovdiv'), ('Graf Ignatievo', 'Graf Ignatievo'), ('Krumovo', 'Krumovo')], default='Plovdiv', max_length=32)),
                ('structural_unit', models.CharField(max_length=52)),
                ('manager', models.CharField(max_length=32)),
                ('start_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Toner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=32)),
                ('model', models.CharField(max_length=32)),
                ('document', models.FileField(upload_to='uploads/%Y%m%d/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=32)),
                ('model', models.CharField(max_length=32)),
                ('serial_number', models.CharField(max_length=32, unique=True)),
                ('toner', models.CharField(max_length=10)),
                ('drum', models.CharField(max_length=10)),
                ('mac_address', models.CharField(max_length=20)),
                ('document', models.FileField(upload_to='uploads/%Y%m%d/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=32)),
                ('model', models.CharField(max_length=32)),
                ('serial_number', models.CharField(max_length=32, unique=True)),
                ('size', models.CharField(max_length=10)),
                ('ports', models.CharField(max_length=50)),
                ('document', models.FileField(upload_to='uploads/%Y%m%d/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=32)),
                ('model', models.CharField(max_length=32)),
                ('serial_number', models.CharField(max_length=32, unique=True)),
                ('cpu', models.CharField(max_length=20)),
                ('ram', models.CharField(max_length=10)),
                ('drive', models.CharField(max_length=20)),
                ('mac_address', models.CharField(max_length=20)),
                ('wifi_mac_address', models.CharField(max_length=20)),
                ('document', models.FileField(upload_to='uploads/%Y%m%d/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Drum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=32)),
                ('model', models.CharField(max_length=32)),
                ('document', models.FileField(upload_to='uploads/%Y%m%d/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=32)),
                ('model', models.CharField(max_length=32)),
                ('serial_number', models.CharField(max_length=32, unique=True)),
                ('cpu', models.CharField(max_length=20)),
                ('ram', models.CharField(max_length=10)),
                ('drive', models.CharField(max_length=20)),
                ('mac_address', models.CharField(max_length=20)),
                ('document', models.FileField(upload_to='uploads/%Y%m%d/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.employee')),
            ],
        ),
    ]
