# Generated by Django 4.1.2 on 2022-12-07 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_drum_user_remove_toner_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='video_card',
            field=models.CharField(default='n/a', max_length=20),
            preserve_default=False,
        ),
    ]
