# Generated by Django 4.1.2 on 2022-12-07 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_laptop_video_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='video_card',
            field=models.CharField(default='n/a', max_length=20),
            preserve_default=False,
        ),
    ]
