# Generated by Django 4.1.2 on 2022-12-07 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_computer_video_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='internet',
            field=models.CharField(choices=[(True, 'Да'), (False, 'Не')], default=False, max_length=5),
        ),
        migrations.AddField(
            model_name='employee',
            name='shares_access',
            field=models.CharField(choices=[('none', 'none'), ('Off', 'Off'), ('OFI', 'OFI'), ('IT', 'IT'), ('oldpcs', 'oldpcs')], default='none', max_length=10),
        ),
        migrations.AlterField(
            model_name='employee',
            name='structural_unit',
            field=models.CharField(choices=[('Търговска дирекция', 'Търговска дирекция'), ('Управление', 'Управление'), ('Финансово-икономическа дирекция', 'Финансово-икономическа дирекция'), ('Ремонт агрегати/Звено мех.', 'Ремонт агрегати/Звено мех.'), ('Офис КИС ЛИС', 'Офис КИС ЛИС'), ('Административна дирекция', 'Административна дирекция'), ('Дирекция Качество', 'Дирекция Качество')], default='Административна дирекция', max_length=52),
        ),
    ]
