# Generated by Django 4.1.2 on 2022-12-13 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_toner_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='drum',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
