# Generated by Django 3.2 on 2023-01-20 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20230119_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='toner',
            name='recomended_quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
