# Generated by Django 3.2 on 2023-01-20 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_toner_recomended_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='drum',
            name='recomended_quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
