# Generated by Django 3.2 on 2023-01-24 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_drum_recomended_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cartridge_name', models.CharField(choices=[(1, 'W1106A (106A)'), (2, 'CRG-724 H'), (3, 'CRG-057 H'), (4, 'CE285A'), (5, 'MLT-D204E'), (6, 'CF217A'), (7, 'TK-130')], default='none', max_length=150)),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
