# Generated by Django 3.2 on 2023-01-24 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='cartridge_name',
            field=models.CharField(choices=[('W1106A (106A)', 1), ('CRG-724 H', 2), ('CRG-057 H', 3), ('CE285A', 4), ('MLT-D204E', 5), ('CF217A', 6), ('TK-130', 7)], default='none', max_length=150),
        ),
    ]
