# Generated by Django 4.1.6 on 2023-02-04 14:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_request_cartridge_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
